repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.21.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./"]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: "v0.1.30"
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      #- id: markdown-link-check ##--> docker run -v .:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:stable /tmp/README.md
